### ISSUE TITLE
PRs for RSD repos checklist

### ISSUE THREAD

**Issue by abelsiqueira** [cffbots/filtering#56]
- [ ] [citation-file-format/cff-converter-python](https://github.com/citation-file-format/cff-converter-python) - yes
- [ ] [citation-file-format/cff-initializer-javascript](https://github.com/citation-file-format/cff-initializer-javascript) - yes
- [ ] [citation-file-format/citation-file-format](https://github.com/citation-file-format/citation-file-format) - yes
- [ ] [CLARIAH/grlc](https://github.com/CLARIAH/grlc) - yes
- [ ] [eWaterCycle/ewatercycle](https://github.com/eWaterCycle/ewatercycle) - yes
- [ ] [fair-workflows/nanopub](https://github.com/fair-workflows/nanopub) - yes
- [ ] [NLeSC/mcfly](https://github.com/NLeSC/mcfly) - yes
- [ ] [phenology/cgc](https://github.com/phenology/cgc) - yes
- [ ] [research-software-directory/research-software-directory](https://github.com/research-software-directory/research-software-directory) - yes
- [ ] [wadpac/GGIR](https://github.com/wadpac/GGIR) - yes
- [ ] [xenon-middleware/xenon](https://github.com/xenon-middleware/xenon) - There are no workflows on main, but there is already an issue on adding cffconvert: https://github.com/xenon-middleware/xenon/issues/686

**Comment by abelsiqueira** [comment]
Last review of open issues: 18-02-2022
